id: 8dec69d62bfd479db29e3b49bceb85cf
title: Toh_147-The_Teaching_on_the_Great_Compassion_of_the_Tathagata-v1
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-057-006
  eft-text-version: 1.2.6 2021
